- name: users | jaziel | remove preinstalled clutter from home directory
  file:
    path: /home/jaziel/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | jaziel | create personal config directories
  tags: dotfiles,dotfiles-jaziel
  file:
    path: /home/jaziel/{{ item.dir }}
    state: directory
    owner: jaziel
    group: jaziel
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
      #    - { dir: .config/bpytop }
      #- { dir: .config/gtk-3.0 }
      #- { dir: .config/terminator }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: repo }
    - { dir: templates }

- name: users | jaziel | copy user-dirs.dirs
  tags: dotfiles,dotfiles-jaziel
  copy:
    src: users/jaziel/user-dirs.dirs
    dest: /home/jaziel/.config/user-dirs.dirs
    owner: jaziel
    group: jaziel
    mode: 0600
  notify: update_xdg

- name: users | jaziel | copy personal config files
  tags: dotfiles,dotfiles-jaziel
  copy:
    src: users/jaziel/{{ item.src }}
    dest: /home/jaziel/{{ item.dest }}
    owner: jaziel
    group: jaziel
    mode: 0600
  with_items:
    #- { src: 'asunder', dest: '.asunder' }
      #- { src: 'bpytop.conf', dest: '.config/bpytop/bpytop.conf' }
      #- { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
      #- { src: 'gvimrc', dest: '.gvimrc' }
      #- { src: ' user-dirs.dirs', dest: '.config/user-dirs.dirs' }
      #- { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
      #- { src: 'terminator_config', dest: '.config/terminator/config' }

# - name: users | jaziel | copy profile image
#   tags: dotfiles,dotfiles-jaziel
#   copy:
#     src: users/jaziel/profile_image.png
#     dest: /var/lib/AccountsService/icons/jaziel.png
#     owner: root
#     group: root
#     mode: 0644
