# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  ## User configs
  - import_tasks: users/jaziel.yml

## desktop environments

  - include_tasks: desktop_environments/mate/appearance.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/caja.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/keybindings.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/packages.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/peripherals.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/terminal.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/mate/workspace_settings.yml
    when: mate is defined and mate == true

  - include_tasks: desktop_environments/gnome/appearance.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/keybindings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/nautilus.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/packages.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/peripherals.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/shell_settings.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/terminal.yml
    when: gnome is defined and gnome == true

  - include_tasks: desktop_environments/gnome/tracker.yml
    when: gnome is defined and gnome == true

  ## system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/scripts.yml
  - import_tasks: system_setup/tweaks.yml

  ## install software
 
  - import_tasks: software/alacritty.yml
  - import_tasks: software/authy.yml
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/codecs.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/protonvpn.yml
  - import_tasks: software/lutris.yml
  - import_tasks: software/minecraft.yml
  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/packer.yml
  - import_tasks: software/remove.yml
  - import_tasks: software/signal.yml
  - import_tasks: software/starship.yml
  - import_tasks: software/solaar.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/steam.yml
  - import_tasks: software/syncthing.yml
  - import_tasks: software/terraform.yml
  - import_tasks: software/thunderbird.yml
  - import_tasks: software/nextcloud-sync.yml
  - import_tasks: software/virtualbox.yml
  - import_tasks: software/vorta.yml
  - import_tasks: software/vlc.yml

  rescue:
    - set_fact: task_failed=true
