<<<<<<< HEAD
- name: user | velociraptor | create
  tags: users
  user:
    name: velociraptor
    system: yes
=======
>>>>>>> b06f81a (changed users, pacakages, inventory, etc.)
- name: users | velociraptor | add public key
  tags: dotfiles,velociraptor,ssh,ssh-keys,users
  authorized_key:
    user: velociraptor
    key: "{{ item }}"
  with_file:
    - users/velociraptor/ssh/velociraptor_id_ed25519.pub

- name: users | velociraptor | add sudoers file
  tags: settings,velociraptor,sudo,system,users
  copy:
    src: users/sudoers_velociraptor
    dest: /etc/sudoers.d/velociraptor
    owner: root
    group: root
    mode: 0440
