- name: software | boto | install package
  tags: boto,packages,pip,python
  become_user: jay
  pip:
    executable: /usr/bin/pip3
    state: latest
    name: boto
  when:
    - ansible_distribution != "Archlinux"
    - chromium is defined
    - chromium == true

