- name: software | firefox | install package
  tags: packages,firefox,workstation-packages
  become: true
  zypper:
    name: firefox
    allow_vendor_change: true
    state: latest
  when: firefox is defined and firefox == true

