- name: software | linode-cli | install package
  tags: packages,linode,pip,python
  become_user: jay
  pip:
    executable: /usr/bin/pip3
    state: latest
    name: linode-cli
  when:
    - ansible_distribution != "Archlinux"
    - chromium is defined
    - chromium == true

