- name: software | protonvpn | install package
  tags: packages,protonvpn,workstation-packages
  become: true
  zypper:
    name: protonvpn-gui
    state: latest
  when: protonvpn is defined and protonvpn == true

