- name: software | thunderbird | install package
  tags: packages,thunderbird,workstation-packages
  become: true
  zypper:
    name: thunderbird
    allow_vendor_change: true
    state: latest
  when: thunderbird is defined and thunderbird == true

