# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always
- name: export TAILSCALE_KEY
  shell: export 'TAILSCALE_KEY="{{ tailscale_auth }}"'

- name: Include artis3n.tailscale
  include_role: 
    name: artis3n.tailscale
  vars:
    # Example pulling the API key from the env vars on the host running Ansible
    tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}" 
    tailscale_args: "{{ tailscale_arg }}"
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - tailscale is defined
    - tailscale == true
- block:
  #- import_tasks: nrpe.yml
  - import_tasks: ufw.yml
  - import_tasks: tailscale.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - tailscale is defined
      - tailscale == true
  - include_tasks: crowdsec.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - crowdsec is defined
      - crowdsec == true

  - include_tasks: unattended_upgrades.yml
    when:
      - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
      - unattended_upgrades is defined
      - unattended_upgrades == true

  rescue:
    - set_fact: task_failed=true
