autofs_master_config: /etc/autofs/auto.master
autofs_nfs_config: /etc/autofs/auto.nfs
cryptsetup_package: cryptsetup
cups_package: cups
font_fira_mono_package: otf-fira-mono
font_hack_ttf_package: ttf-hack
font_inconsolata_package: ttf-inconsolata
font_noto_emoji_package: noto-fonts-emoji
font_terminus_package: terminus-font
font_jetbrains_package: jetbrains-mono-fonts
jay_user_group: users
libnotify_package: libnotify4
mpv_package: mpv
network_manager_openvpn_package: networkmanager-openvpn
network_manager_package: networkmanager
network_manager_pptp_package: networkmanager-pptp
network_manager_vpnc_package: networkmanager-vpnc
packer_version: 1.6.5
steam_package: steam
wireless_tools_package: wireless_tools
wpa_supplicant_package: wpa_supplicant
