# - name: Check if file is not a symbolic link
#   stat:
#     path: $HOME/.bashrc
#   register: file_stat
# 
# - name: back up .bashrc
#   become_user: jaziel
#   shell: mv $HOME/.bashrc $HOME/.bashrc.bk
#   when: file_stat.stat.islink is not defined or file_stat.stat.islink == false
- name: file | create .dot |
  tags: dotfiles,stows
  file:
    path: $HOME/.config/.dot
    state: directory
    owner: jaziel
    group: jaziel
    mode: 0700

- name: cp stow files
  tags: stow
  copy:
    src: files/config/"{{ stow_config }}"
    dest: $HOME/.config/.dot 
- name: stow dotfiles
  become_user: jaziel
  tags: "install,stow"
  stow:
    state: supress
    package: "{{ stow_config }}"
    dir: $HOME/.config/.dot
    target: $HOME

